In [10]:
import numpy as np
import pandas as pd
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dropout, Dense
from tensorflow.keras.optimizers import Adam


In [11]:
dataset=pd.read_csv('iris.csv')

In [12]:
X = dataset.iloc[:,1:5].values
y = dataset.iloc[:,5].values
#print(y)
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)
print(y1.shape)
Y = pd.get_dummies(y1).values
print(Y.shape)

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X,Y,test_size=0.2,random_state=0) 

(150,)
(150, 3)


In [13]:
model=Sequential()
model.add(Dense(10,input_shape=(4,),activation='tanh'))
model.add(Dense(8,activation='tanh'))
model.add(Dense(6,activation='tanh'))
model.add(Dense(3,activation='softmax'))

model.compile(Adam(lr=0.04),'categorical_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 10)                50        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_6 (Dense)              (None, 6)                 54        
_________________________________________________________________
dense_7 (Dense)              (None, 3)                 21        
Total params: 213
Trainable params: 213
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(X_train,y_train,batch_size=10,epochs=10)
y_pred = model.predict(X_test)

y_test_class = np.argmax(y_test,axis=1)
y_pred_class = np.argmax(y_pred,axis=1)

Epoch 1/10
120/120 [==============================] - 0s 3ms/sample - loss: 0.6421 - acc: 0.7000
Epoch 2/10
120/120 [==============================] - 0s 283us/sample - loss: 0.3494 - acc: 0.9333
Epoch 3/10
120/120 [==============================] - 0s 225us/sample - loss: 0.2092 - acc: 0.9083
Epoch 4/10
120/120 [==============================] - 0s 225us/sample - loss: 0.4364 - acc: 0.8167
Epoch 5/10
120/120 [==============================] - 0s 508us/sample - loss: 0.4430 - acc: 0.7750
Epoch 6/10
120/120 [==============================] - 0s 358us/sample - loss: 0.1899 - acc: 0.9333
Epoch 7/10
120/120 [==============================] - 0s 308us/sample - loss: 0.1827 - acc: 0.9167
Epoch 8/10
120/120 [==============================] - 0s 317us/sample - loss: 0.1236 - acc: 0.9667
Epoch 9/10
120/120 [==============================] - 0s 358us/sample - loss: 0.1084 - acc: 0.9500
Epoch 10/10
120/120 [==============================] - 0s 258us/sample - loss: 0.1422 - acc: 0.9333


In [15]:
from sklearn.metrics import classification_report,confusion_matrix
print(classification_report(y_test_class,y_pred_class))
print(confusion_matrix(y_test_class,y_pred_class))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        11
          1       1.00      1.00      1.00        13
          2       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]
